let shopItemsData = [
  {
    id: "voiceassistpro",
    name: "VoiceAssist Pro (White)",
    price: 105,
    desc: "Classic analog style meets modern tech. Features AI Voice assistant for hands-free control and seamless call management.",
    img: "images/img-5.jpg",
  },
  {
    id: "purewhite2",
    name: "Pure White 2",
    price: 75,
    desc: "A clean, minimalist design for essential health tracking. Perfect readability and optimal comfort for daily use.",
    img: "images/img-6.jpg",
  },
  {
    id: "gobasicblue",
    name: "GoBasic (Blue)",
    price: 49,
    desc: "The essentials on your wrist. Time, date, and step tracking in a compact and lightweight format. Ideal for beginners.",
    img: "images/img-7.jpg",
  },
  {
    id: "conceptarc",
    name: "Concept Arc",
    price: 129,
    desc: "A unique curved display for an immersive experience. Access your apps and notifications on a panoramic screen.",
    img: "images/img-8.jpg",
  },
];


// let shopItemsData = [
//   {
//     id: "aurafitpro",
//     name: "AuraFit Pro (Beige)",
//     price: 89,
//     desc: "Elegant and smart. Track your health with precision (BPM, Kcal, steps) and receive your notifications in style. Comfortable strap.",
//     img: "images/img-1.jpg",
//   },
//   {
//     id: "vividcallblack",
//     name: "VividCall Elite (Black)",
//     price: 79,
//     desc: "Make and receive calls directly from your wrist. Its vibrant screen and multiple watch faces make it a prime choice.",
//     img: "images/img-2.jpg",
//   },
//   {
//     id: "connectmauve",
//     name: "Connect-Me (Mauve)",
//     price: 69,
//     desc: "Stay connected, simply. Clear call functions and an intuitive interface. Comes with an extra black Milanese strap.",
//     img: "images/img-3.jpg",
//   },
//   {
//     id: "feelflora",
//     name: "FeelNever Flora (Pink)",
//     price: 99,
//     desc: "A unique design with its floral dial and octagonal case. Perfect for those who seek both elegance and technology.",
//     img: "images/img-4.jpg",
//   },
//   {
//     id: "voiceassistpro",
//     name: "VoiceAssist Pro (White)",
//     price: 105,
//     desc: "Classic analog style meets modern tech. Features AI Voice assistant for hands-free control and seamless call management.",
//     img: "images/img-5.jpg",
//   },
//   {
//     id: "purewhite2",
//     name: "Pure White 2",
//     price: 75,
//     desc: "A clean, minimalist design for essential health tracking. Perfect readability and optimal comfort for daily use.",
//     img: "images/img-6.jpg",
//   },
//   {
//     id: "gobasicblue",
//     name: "GoBasic (Blue)",
//     price: 49,
//     desc: "The essentials on your wrist. Time, date, and step tracking in a compact and lightweight format. Ideal for beginners.",
//     img: "images/img-7.jpg",
//   },
//   {
//     id: "conceptarc",
//     name: "Concept Arc",
//     price: 129,
//     desc: "A unique curved display for an immersive experience. Access your apps and notifications on a panoramic screen.",
//     img: "images/img-8.jpg",
//   },
//   {
//     id: "fittrackslim",
//     name: "FitTrack Slim",
//     price: 59,
//     desc: "Discreet, slim, and designed for sports. This band tracks your activities and sleep without getting in the way. Your performance partner.",
//     img: "images/img-9.jpg",
//   },
//   {
//     id: "versastyle",
//     name: "VersaStyle (Black)",
//     price: 95,
//     desc: "A versatile style that matches all your outfits. Complete health tracking, active zone minutes, and smart notifications.",
//     img: "images/img-10.jpg",
//   },
//   {
//     id: "aurafitrose",
//     name: "AuraFit Pro (Rose Gold)",
//     price: 89,
//     desc: "All the features of the AuraFit Pro in a stunning Rose Gold finish. Manage your calls and well-being with a touch of glamour.",
//     img: "images/img-11.jpg",
//   },
//   {
//     id: "matrixoswhite",
//     name: "Matrix OS (White)",
//     price: 119,
//     desc: "Navigate your apps with a fluid and intuitive 'Matrix' interface. Fast processing power in a chrome-finished case.",
//     img: "images/img-12.jpg",
//   },
// ];